"""Pull this service's .env from OpenBao (QA / testserv) and write it locally.

Pre-launch step: run it right before starting the service (or a one-off script) so
the local .env is regenerated from the central OpenBao source of truth. It must run
before the app imports src.config (which reads .env at import time).

OpenBao is provisioned with a SPLIT layout (see Sentrifugo-DevOps/openbao/provision.sh):
  * secret/shared/datastores  — Mongo/Valkey/Neo4j/RabbitMQ creds shared by ALL services
  * secret/payroll  — THIS service's own (non-datastore) keys
This script MERGES both (shared first, service keys override) so the produced .env
is complete. The local BAO_* bootstrap keys (connection + token) are NOT stored in
OpenBao, so they are preserved from the existing .env. The existing file is backed
up to .env.bak first.

Usage (from repo root):
    python scripts/pull_env_from_openbao.py            # writes ./.env
    python scripts/pull_env_from_openbao.py --out .env.local
    python scripts/pull_env_from_openbao.py --stdout   # print, don't write

Connection config resolves in this order: real env var -> ./.env -> default.
    BAO_ADDR                    OpenBao address (default: http://openbao:8200)
    BAO_TOKEN                   token with read access (or a BAO_TOKEN_FILE / .bao-token file)
    BAO_KV_MOUNT / BAO_KV_PATH  KV mount + path (default: secret / payroll)
    BAO_KV_SHARED_PATH          shared datastore path (default: shared/datastores)
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

try:
    import hvac
except ImportError:
    sys.exit("hvac is not installed. Run: pip install hvac  (or pip install -r requirements.txt)")

# Default is the compose service name `openbao` — works from INSIDE a container on
# the same docker network as OpenBao (how the services reach it). On the QA host
# itself use http://127.0.0.1:8200; from a laptop use an SSH tunnel. testserv only
# publishes OpenBao to 127.0.0.1:8200, so the public IP 168.144.29.6 will NOT work.
# Override anytime with the BAO_ADDR env var.
DEFAULT_ADDR = "http://openbao:8200"
DEFAULT_MOUNT = "secret"
DEFAULT_PATH = "payroll"
DEFAULT_SHARED_PATH = "shared/datastores"
# Keys with this prefix are local bootstrap config, preserved across pulls.
BOOTSTRAP_PREFIX = "BAO_"


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.is_file():
        return data
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key.startswith("export "):
            key = key[len("export "):].strip()
        if key:
            data[key] = value.strip()
    return data


def _local_env() -> dict[str, str]:
    return parse_env_file(Path(".env"))


def resolve_config() -> tuple[str, str, str, str]:
    local = _local_env()
    addr = os.environ.get("BAO_ADDR") or local.get("BAO_ADDR") or DEFAULT_ADDR
    mount = os.environ.get("BAO_KV_MOUNT") or local.get("BAO_KV_MOUNT") or DEFAULT_MOUNT
    path = os.environ.get("BAO_KV_PATH") or local.get("BAO_KV_PATH") or DEFAULT_PATH
    shared = os.environ.get("BAO_KV_SHARED_PATH") or local.get("BAO_KV_SHARED_PATH") or DEFAULT_SHARED_PATH
    return addr, mount, path, shared


def resolve_token() -> str:
    token = os.environ.get("BAO_TOKEN")
    if token:
        return token.strip()
    token_file = Path(os.environ.get("BAO_TOKEN_FILE", ".bao-token"))
    if token_file.is_file():
        return token_file.read_text(encoding="utf-8").strip()
    token = _local_env().get("BAO_TOKEN")
    if token:
        return token.strip()
    sys.exit(
        "No OpenBao token. Set $BAO_TOKEN, add BAO_TOKEN to .env, or use a .bao-token "
        "file (the root token is printed by openbao/scripts/init.sh)."
    )


def _read_kv(client: "hvac.Client", mount: str, path: str) -> dict[str, str]:
    resp = client.secrets.kv.v2.read_secret_version(mount_point=mount, path=path, raise_on_deleted_version=True)
    return resp["data"]["data"] or {}


def read_merged_secrets(client: "hvac.Client", mount: str, path: str, shared: str) -> dict[str, str]:
    """Shared datastore creds first, then this service's keys (service overrides shared)."""
    merged: dict[str, str] = {}
    try:
        merged.update(_read_kv(client, mount, shared))
    except Exception as exc:  # shared path may not exist in a minimal setup
        print(f"WARN: could not read shared datastore path {mount}/{shared}: {exc}")
    merged.update(_read_kv(client, mount, path))
    return merged


def render_env(secrets: dict[str, str], preserved: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/pull_env_from_openbao.py from OpenBao. Every secret",
        "# here comes from OpenBao (secret/shared/datastores + this service's path) —",
        "# edit it there (or edit + re-seed), because this file is overwritten on every",
        "# pull. The OpenBao token itself is NOT stored here; it lives in the gitignored",
        "# .bao-token file (or the $BAO_TOKEN env var).",
        "",
    ]
    for key in sorted(secrets):
        lines.append(f"{key}={secrets[key]}")
    if preserved:
        lines.append("")
        lines.append("# --- local OpenBao bootstrap config (not stored in OpenBao) ---")
        for key in sorted(preserved):
            lines.append(f"{key}={preserved[key]}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Pull .env from OpenBao KV v2 (shared + service).")
    ap.add_argument("--out", default=".env", help="output .env path (default: .env)")
    ap.add_argument("--stdout", action="store_true", help="print to stdout instead of writing a file")
    args = ap.parse_args()

    addr, mount, path, shared = resolve_config()

    client = hvac.Client(url=addr, token=resolve_token())
    if not client.is_authenticated():
        sys.exit(f"OpenBao auth failed at {addr}. Check BAO_TOKEN / server reachability.")

    secrets = read_merged_secrets(client, mount, path, shared)
    if not secrets:
        sys.exit(f"No secrets found at {mount}/{path} (+{shared}). Seed them first with seed_env_to_openbao.py.")

    out = Path(args.out)
    preserved = {k: v for k, v in parse_env_file(out).items() if k.startswith(BOOTSTRAP_PREFIX)}
    secrets = {k: v for k, v in secrets.items() if not k.startswith(BOOTSTRAP_PREFIX)}

    content = render_env(secrets, preserved)

    if args.stdout:
        sys.stdout.write(content)
        return

    if out.exists():
        backup = out.with_suffix(out.suffix + ".bak")
        backup.write_text(out.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"Backed up existing {out} -> {backup}")
    out.write_text(content, encoding="utf-8")
    kept = f" (+{len(preserved)} preserved BAO_* keys)" if preserved else ""
    print(f"Wrote {len(secrets)} keys from {addr}  {mount}/{{{shared},{path}}} -> {out}{kept}")


if __name__ == "__main__":
    main()
