// This file was previously generated by shadcn for react-hook-form integration.
// It is kept here as a placeholder but is NOT used in this project.
// All forms use @tanstack/react-form instead.
// DO NOT DELETE — shadcn CLI may regenerate this file on component installs.
export {};
