from enum import IntEnum


class DebugLevel(IntEnum):
    EMPLOYEE = 1
    MANAGER = 2
    HR = 3
    ADMIN = 4


class EventTypes:
    # Business events (inbound from IAM)
    USER_CREATED = "USER_CREATED"
    DEPARTMENT_SYNCED = "DEPARTMENT_SYNCED"
    BUSINESS_UNIT_SYNCED = "BUSINESS_UNIT_SYNCED"

    # Audit event type
    AUDIT = "AUDIT"

    # Audit actions
    LEAVE_APPLIED = "LEAVE_APPLIED"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"
    LEAVE_CANCELLED = "LEAVE_CANCELLED"

    # Holiday plan audit actions
    HOLIDAY_PLAN_CREATED = "HOLIDAY_PLAN_CREATED"
    HOLIDAY_PLAN_UPDATED = "HOLIDAY_PLAN_UPDATED"
    HOLIDAY_PLAN_DELETED = "HOLIDAY_PLAN_DELETED"
    HOLIDAY_CREATED = "HOLIDAY_CREATED"
    HOLIDAY_UPDATED = "HOLIDAY_UPDATED"
    HOLIDAY_DELETED = "HOLIDAY_DELETED"
