// ─── Enums / unions ───────────────────────────────────────────────────────────

export type Gender = 'male' | 'female' | 'other';
export type MaritalStatus = 'single' | 'married' | 'divorced' | 'widowed';
export type EmploymentType = 'full-time' | 'contract' | 'internship';
export type EmploymentStatus = 'notice-period' | 'probation' | 'permanent' | 'absconded' | 'exit' | 'retired' | 'terminated';
// Allocation / resourcing state — independent of the employment lifecycle status.
export type ProjectStatus = 'allocated-to-project' | 'bench' | 'long-leave';

// ─── Address ──────────────────────────────────────────────────────────────────

export interface Address {
  addressLine1: string;
  addressLine2: string;
  city: string;
  country: string;
  state: string;
  postalCode: string;
}

export const EMPTY_ADDRESS: Address = {
  addressLine1: '',
  addressLine2: '',
  city: '',
  country: '',
  state: '',
  postalCode: '',
};

// ─── Repeatable row types ─────────────────────────────────────────────────────

export interface WorkExperienceRow {
  companyName: string;
  jobTitle: string;
  fromDate: string;
  toDate: string;
  jobDescription: string;
  relevant: string;
}

export const EMPTY_EXPERIENCE: WorkExperienceRow = {
  companyName: '',
  jobTitle: '',
  fromDate: '',
  toDate: '',
  jobDescription: '',
  relevant: '',
};

export interface DependentRow {
  name: string;
  relationship: string;
  dateOfBirth: string;
}

export const EMPTY_DEPENDENT: DependentRow = {
  name: '',
  relationship: '',
  dateOfBirth: '',
};

export interface EducationRow {
  instituteName: string;
  degree: string;
  specialization: string;
  dateOfCompletion: string;
}

export const EMPTY_EDUCATION: EducationRow = {
  instituteName: '',
  degree: '',
  specialization: '',
  dateOfCompletion: '',
};

// ─── Identity field (dynamic per country) ─────────────────────────────────────

export interface IdentityField {
  label: string;
  value: string;
}

// ─── Emergency Contact ───────────────────────────────────────────────────────

export interface EmergencyContactRow {
  contactName: string;
  contactNumber: string;
  relationship: string;
}

export const EMPTY_EMERGENCY_CONTACT: EmergencyContactRow = {
  contactName: '',
  contactNumber: '',
  relationship: '',
};

// ─── Bank Details ─────────────────────────────────────────────────────────────

export interface BankDetailsValues {
  accountHolderName: string;
  accountNumber: string;
  ifscCode: string;
  bankName: string;
}

export const EMPTY_BANK_DETAILS: BankDetailsValues = {
  accountHolderName: '',
  accountNumber: '',
  ifscCode: '',
  bankName: '',
};

// ─── Full employee form ───────────────────────────────────────────────────────

export interface EmployeeFormValues {
  // Basic Details (emp_code is auto-generated by server, not editable)
  workEmail: string;
  firstName: string;
  middleName: string;
  lastName: string;

  // Work Info
  businessUnit: string;
  department: string;
  designation: string;
  role: string;
  sourceOfHire: string;
  l1Manager: string;
  l2Manager: string;
  currentExp: string;
  totalExp: string;
  employmentType: string;
  employmentStatus: string;
  projectStatus: string;
  dateOfJoining: string;
  dateOfExit: string;

  // Compensation
  ctc: string;
  currency: string;

  // Personal Details
  dob: string;
  gender: string;
  maritalStatus: string;
  aboutMe: string;

  // Identity Info
  identityFields: IdentityField[];

  // Bank Details
  bankDetails: BankDetailsValues;

  // Contact
  workPhoneExtension: string;
  workPhone: string;
  personalPhone: string;
  personalEmail: string;
  seatLocation: string;

  // Address
  permanentAddress: Address;
  presentAddress: Address;
  sameAsPermanent: boolean;

  // Emergency Contacts
  emergencyContacts: EmergencyContactRow[];

  // Repeatable sections
  workExperience: WorkExperienceRow[];
  dependents: DependentRow[];
  education: EducationRow[];
}

export const EMPTY_EMPLOYEE_FORM: EmployeeFormValues = {
  workEmail: '',
  firstName: '',
  middleName: '',
  lastName: '',

  businessUnit: '',
  department: '',
  designation: '',
  role: '',
  sourceOfHire: '',
  l1Manager: '',
  l2Manager: '',
  currentExp: '',
  totalExp: '',
  employmentType: '',
  employmentStatus: '',
  projectStatus: '',
  dateOfJoining: '',
  dateOfExit: '',

  ctc: '',
  currency: '',

  dob: '',
  gender: '',
  maritalStatus: '',
  aboutMe: '',

  identityFields: [],

  bankDetails: { ...EMPTY_BANK_DETAILS },

  workPhoneExtension: '',
  workPhone: '',
  personalPhone: '',
  personalEmail: '',
  seatLocation: '',

  permanentAddress: { ...EMPTY_ADDRESS },
  presentAddress: { ...EMPTY_ADDRESS },
  sameAsPermanent: false,

  emergencyContacts: [{ ...EMPTY_EMERGENCY_CONTACT }],
  workExperience: [{ ...EMPTY_EXPERIENCE }],
  dependents: [{ ...EMPTY_DEPENDENT }],
  education: [{ ...EMPTY_EDUCATION }],
};
